server:
  port: 9999
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: host_route
        uri: http://www.baidu.com
        predicates:
        - Path=/a/**
        filters:
        - StripPrefix=1
#      - id: header
#        uri: http://localhost:8888/header
#        filters:
#        - AddRequestHeader=header, addHeader
#        - AddRequestParameter=param, addParam
#        predicates:
#        - Path=/jd
redis:
  host: 127.0.0.1
  port: 6379
  pool:
    max-active: 8
    max-wait: 1
    max-idle: 8
    min-idle: 0
  timeout: 0